### ISSUE TITLE
Map Interactivity

### ISSUE THREAD

**Issue by ajchu28** [net-art-uchicago/cta-file-sharing#7]
I'm not exactly sure how this will fit in with everyone else's components at the moment, but I'll be working on the bullet point of the planning for "Map Interaction." My basic initial plan is to generate the base map for the city of Chicago and add basic controls, then at some point incorporate the work from "bus tracking" as well so you can highlight the routes that the person is on. This will probably be the base to display some other information at some point as well? 
I plan on using Mapbox and their API Mapbox GL JS.

**Comment by nbriz** [comment]
@ajchu28 cool! do u have images of what u want the design to look like? it's important to draft that up first, before writing any code. once u do, share the image here so i can take a look + comment on it + approve it before u start coding

**Comment by ajchu28** [comment]
<img width="520" alt="Screen Shot 2022-11-08 at 3 27 50 PM" src="https://user-images.githubusercontent.com/84213588/200679144-ad0b929f-5962-4259-af73-0b66d1b83bca.png">

The styling itself might depend on what the rest of the team does, but as far as basic navigation and experience of the map, this is what I'm envisioning.

This is a bit more in depth about the components comprising the map:

Base Map:
- Created in Mapbox 
- Can change the colors, what appears, layers etc

Layers (bus routes):
- Also hosted in Mapbox
- Can toggle on and off depending on user input of what bus they’re riding/location 

Poem Location (lat, long, text, author, time):
- Drops a pin for the poem at the given location
- When you click on the point, the poem appears

Map Navigation:
- Regular pinch/swipe navigation
- Poems aggregate or disaggregate depending on zoom level
- Bubbles appear proportionally larger/smaller

**Comment by ajchu28** [comment]
Base Map:
https://api.mapbox.com/styles/v1/ajchu28/cla8p13jr002s14qvhnow3727.html?title=view&access_token=pk.eyJ1IjoiYWpjaHUyOCIsImEiOiJja3o2M3MzMWswd200MnZwNGdieTNlaHRjIn0.BePZiTybP8rLoo6yQKon_w&zoomwheel=true&fresh=true#2/37.75/-92.25

**Comment by ajchu28** [comment]
Example: https://ajchu28.github.io/mapwebsite/index.html

**Comment by ajchu28** [comment]
@nbriz What is the best way for me and Ying to collaborate on the code for this? Are we able to open a branch or something to work together on the code?

**Comment by nbriz** [comment]
@ajchu28 have u decided whose gonna wok on which part? 
one suggestion i might make is u work on the JS/mapbox part (since u'v got experience w/that) while Ying maybe works on some of the other GUI elements. it's my understanding that those popups (for example) need to be created/styled w/HTML/CSS, am i right? if so u could create a branch w/the map functioning, while Ying creates a branch purely focused on creating + styling those elements (temporarily staged in their own HTML file). u could both then submit PRs for ur respective branches, then in class u could both work together to "merge" both ur contributions together on a new branch.

does that make sense? main idea is that u work on u respective parts on separate branches, && then we create a third branch purely for the purpose of merging those together
